# Homebrew formula for codetracer-cardano-recorder.
#
# Generated by codetracer-launcher/packaging/recorder-templates/generate.py
# from codetracer-cardano-recorder/packaging/recorder-metadata.yml.
# DO NOT edit this file by hand — re-run the generator instead.
#
# Per CodeTracer Launcher §11 (M11), the per-recorder Homebrew
# formula installs the recorder binary only. The launcher (`ct`) is
# distributed separately via `brew install codetracer` from the M9
# tap.
#
# At publish time, the sha256 placeholders are rewritten by
# .github/workflows/publish-homebrew.yml using the GitHub-release
# artifacts uploaded by the recorder's release workflow.

class CodetracerCardanoRecorder < Formula
  desc "CodeTracer recorder for Cardano Plutus / UPLC smart contracts"
  homepage "https://github.com/metacraft-labs/codetracer-cardano-recorder"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/metacraft-labs/codetracer-cardano-recorder/releases/download/v0.1.0/codetracer-cardano-recorder-darwin-aarch64"
      sha256 "REPLACE_AT_PUBLISH_TIME_darwin_aarch64"
    end
    on_intel do
      url "https://github.com/metacraft-labs/codetracer-cardano-recorder/releases/download/v0.1.0/codetracer-cardano-recorder-darwin-x86_64"
      sha256 "REPLACE_AT_PUBLISH_TIME_darwin_x86_64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/metacraft-labs/codetracer-cardano-recorder/releases/download/v0.1.0/codetracer-cardano-recorder-linux-aarch64"
      sha256 "REPLACE_AT_PUBLISH_TIME_linux_aarch64"
    end
    on_intel do
      url "https://github.com/metacraft-labs/codetracer-cardano-recorder/releases/download/v0.1.0/codetracer-cardano-recorder-linux-x86_64"
      sha256 "REPLACE_AT_PUBLISH_TIME_linux_x86_64"
    end
  end

  # Source-build fallback. Each blockchain recorder uses Cargo;
  # depend on the Rust toolchain for the head path.
  head do
    url "https://github.com/metacraft-labs/codetracer-cardano-recorder.git", branch: "main"
    depends_on "rust" => :build
  end

  depends_on "zstd"

  def install
    if build.head?
      # Source build path — cargo produces the binary at
      # target/release/codetracer-cardano-recorder.
      system "cargo", "build", "--release", "--locked", "--bin", "codetracer-cardano-recorder"
      bin.install "target/release/codetracer-cardano-recorder" => "codetracer-cardano-recorder"
    else
      # Pre-built binary path — the downloaded artifact lands as
      # `codetracer-cardano-recorder-<target>`; rename to the canonical name.
      bin.install Dir["codetracer-cardano-recorder*"].first => "codetracer-cardano-recorder"
    end
  end

  test do
    # Smoke test: the recorder responds to --version (or --help, if
    # the recorder uses Clap's default --help convention). Asserting
    # a non-empty exit-0 output catches the "binary segfaults
    # immediately" failure mode without overconstraining the version
    # string.
    output = shell_output("#{bin}/codetracer-cardano-recorder --version 2>&1", 0)
    assert_match(/codetracer-cardano-recorder/, output)
  end
end
