name: Windows Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  windows-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Install capnproto
        shell: pwsh
        run: choco install capnproto -y
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test
